# Switch to 'postgresql' in config/database.yml before running 'docker-compose up'
version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54333:5432"
  web:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/sample_rails_application
      - /sample_rails_application/node_modules
      - node_modules:/usr/src/app/node_modules
      - system_bundler_cache:/usr/local/bundle
      - user_bundler_cache:/home/app/.gem
      - user_cache:/home/app/.cache
    ports:
      - "3000:3000"
      # Ports required for debugging
      - "1234:1234"
      - "26166:26168"
    depends_on:
      - db

volumes:
  system_bundler_cache:
  user_bundler_cache:
  user_cache:
  postgres_data:
  node_modules: